// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// CookieWithDurationAdder is an autogenerated mock type for the CookieWithDurationAdder type
type CookieWithDurationAdder struct {
	mock.Mock
}

// AddCookieWithDuration provides a mock function with given fields: name, value, duration, w
func (_m *CookieWithDurationAdder) AddCookieWithDuration(name string, value string, duration string, w http.ResponseWriter) error {
	ret := _m.Called(name, value, duration, w)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, http.ResponseWriter) error); ok {
		r0 = rf(name, value, duration, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCookieWithDurationAdder interface {
	mock.TestingT
	Cleanup(func())
}

// NewCookieWithDurationAdder creates a new instance of CookieWithDurationAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCookieWithDurationAdder(t mockConstructorTestingTNewCookieWithDurationAdder) *CookieWithDurationAdder {
	mock := &CookieWithDurationAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
