// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CookieAdder is an autogenerated mock type for the CookieAdder type
type CookieAdder struct {
	mock.Mock
}

// AddCookie provides a mock function with given fields: name, value, expireTime, w
func (_m *CookieAdder) AddCookie(name string, value string, expireTime time.Time, w http.ResponseWriter) {
	_m.Called(name, value, expireTime, w)
}

type mockConstructorTestingTNewCookieAdder interface {
	mock.TestingT
	Cleanup(func())
}

// NewCookieAdder creates a new instance of CookieAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCookieAdder(t mockConstructorTestingTNewCookieAdder) *CookieAdder {
	mock := &CookieAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
