// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// CookieCleaner is an autogenerated mock type for the CookieCleaner type
type CookieCleaner struct {
	mock.Mock
}

// ClearCookie provides a mock function with given fields: name, w
func (_m *CookieCleaner) ClearCookie(name string, w http.ResponseWriter) {
	_m.Called(name, w)
}

type mockConstructorTestingTNewCookieCleaner interface {
	mock.TestingT
	Cleanup(func())
}

// NewCookieCleaner creates a new instance of CookieCleaner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCookieCleaner(t mockConstructorTestingTNewCookieCleaner) *CookieCleaner {
	mock := &CookieCleaner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
