// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// OrderChanger is an autogenerated mock type for the OrderChanger type
type OrderChanger struct {
	mock.Mock
}

// Change provides a mock function with given fields: ctx, order
func (_m *OrderChanger) Change(ctx context.Context, order *entity.Order) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOrderChanger interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderChanger creates a new instance of OrderChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderChanger(t mockConstructorTestingTNewOrderChanger) *OrderChanger {
	mock := &OrderChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
