// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OrderRemover is an autogenerated mock type for the OrderRemover type
type OrderRemover struct {
	mock.Mock
}

// Remove provides a mock function with given fields: ctx, number
func (_m *OrderRemover) Remove(ctx context.Context, number string) error {
	ret := _m.Called(ctx, number)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, number)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOrderRemover interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderRemover creates a new instance of OrderRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderRemover(t mockConstructorTestingTNewOrderRemover) *OrderRemover {
	mock := &OrderRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
