// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// OrderAdder is an autogenerated mock type for the OrderAdder type
type OrderAdder struct {
	mock.Mock
}

type OrderAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderAdder) EXPECT() *OrderAdder_Expecter {
	return &OrderAdder_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, order
func (_m *OrderAdder) Add(ctx context.Context, order *entity.Order) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderAdder_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type OrderAdder_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//  - ctx context.Context
//  - order *entity.Order
func (_e *OrderAdder_Expecter) Add(ctx interface{}, order interface{}) *OrderAdder_Add_Call {
	return &OrderAdder_Add_Call{Call: _e.mock.On("Add", ctx, order)}
}

func (_c *OrderAdder_Add_Call) Run(run func(ctx context.Context, order *entity.Order)) *OrderAdder_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Order))
	})
	return _c
}

func (_c *OrderAdder_Add_Call) Return(_a0 error) *OrderAdder_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewOrderAdder interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderAdder creates a new instance of OrderAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderAdder(t mockConstructorTestingTNewOrderAdder) *OrderAdder {
	mock := &OrderAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
