// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// OrderGetter is an autogenerated mock type for the OrderGetter type
type OrderGetter struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, number
func (_m *OrderGetter) Get(ctx context.Context, number string) (*entity.Order, error) {
	ret := _m.Called(ctx, number)

	var r0 *entity.Order
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Order); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewOrderGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderGetter creates a new instance of OrderGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderGetter(t mockConstructorTestingTNewOrderGetter) *OrderGetter {
	mock := &OrderGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
