// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// RowQuerier is an autogenerated mock type for the RowQuerier type
type RowQuerier struct {
	mock.Mock
}

// QueryRowContext provides a mock function with given fields: ctx, db, query, args
func (_m *RowQuerier) QueryRowContext(ctx context.Context, db *sql.DB, query string, args ...interface{}) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, db, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(context.Context, *sql.DB, string, ...interface{}) *sql.Row); ok {
		r0 = rf(ctx, db, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

type mockConstructorTestingTNewRowQuerier interface {
	mock.TestingT
	Cleanup(func())
}

// NewRowQuerier creates a new instance of RowQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRowQuerier(t mockConstructorTestingTNewRowQuerier) *RowQuerier {
	mock := &RowQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
