// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserAddWithdrawer is an autogenerated mock type for the UserAddWithdrawer type
type UserAddWithdrawer struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, userID
func (_m *UserAddWithdrawer) Get(ctx context.Context, userID uuid.UUID) (*entity.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Withdraw provides a mock function with given fields: ctx, user, sum
func (_m *UserAddWithdrawer) Withdraw(ctx context.Context, user *entity.User, sum float32) error {
	ret := _m.Called(ctx, user, sum)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User, float32) error); ok {
		r0 = rf(ctx, user, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserAddWithdrawer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserAddWithdrawer creates a new instance of UserAddWithdrawer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserAddWithdrawer(t mockConstructorTestingTNewUserAddWithdrawer) *UserAddWithdrawer {
	mock := &UserAddWithdrawer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
