// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// UserByCredentialGetter is an autogenerated mock type for the UserByCredentialGetter type
type UserByCredentialGetter struct {
	mock.Mock
}

// GetByCredential provides a mock function with given fields: ctx, login, passwordHash
func (_m *UserByCredentialGetter) GetByCredential(ctx context.Context, login string, passwordHash string) (*entity.User, error) {
	ret := _m.Called(ctx, login, passwordHash)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.User); ok {
		r0 = rf(ctx, login, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, login, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserByCredentialGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserByCredentialGetter creates a new instance of UserByCredentialGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserByCredentialGetter(t mockConstructorTestingTNewUserByCredentialGetter) *UserByCredentialGetter {
	mock := &UserByCredentialGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
