// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// UserTransactionalAccrualer is an autogenerated mock type for the UserTransactionalAccrualer type
type UserTransactionalAccrualer struct {
	mock.Mock
}

// Accrual provides a mock function with given fields: ctx, user, accrual
func (_m *UserTransactionalAccrualer) Accrual(ctx context.Context, user *entity.User, accrual float32) error {
	ret := _m.Called(ctx, user, accrual)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User, float32) error); ok {
		r0 = rf(ctx, user, accrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithinTransaction provides a mock function with given fields: ctx, tFunc
func (_m *UserTransactionalAccrualer) WithinTransaction(ctx context.Context, tFunc func(context.Context) error) error {
	ret := _m.Called(ctx, tFunc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, tFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserTransactionalAccrualer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserTransactionalAccrualer creates a new instance of UserTransactionalAccrualer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserTransactionalAccrualer(t mockConstructorTestingTNewUserTransactionalAccrualer) *UserTransactionalAccrualer {
	mock := &UserTransactionalAccrualer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
