// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// UserPasswordChanger is an autogenerated mock type for the UserPasswordChanger type
type UserPasswordChanger struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: ctx, user
func (_m *UserPasswordChanger) ChangePassword(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserPasswordChanger interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserPasswordChanger creates a new instance of UserPasswordChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserPasswordChanger(t mockConstructorTestingTNewUserPasswordChanger) *UserPasswordChanger {
	mock := &UserPasswordChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
