// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// UserWithdrawer is an autogenerated mock type for the UserWithdrawer type
type UserWithdrawer struct {
	mock.Mock
}

// Withdraw provides a mock function with given fields: ctx, user, sum
func (_m *UserWithdrawer) Withdraw(ctx context.Context, user *entity.User, sum float32) error {
	ret := _m.Called(ctx, user, sum)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User, float32) error); ok {
		r0 = rf(ctx, user, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserWithdrawer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserWithdrawer creates a new instance of UserWithdrawer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserWithdrawer(t mockConstructorTestingTNewUserWithdrawer) *UserWithdrawer {
	mock := &UserWithdrawer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
