// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WithdrawGetter is an autogenerated mock type for the WithdrawGetter type
type WithdrawGetter struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, withdrawID
func (_m *WithdrawGetter) Get(ctx context.Context, withdrawID uuid.UUID) (*entity.Withdraw, error) {
	ret := _m.Called(ctx, withdrawID)

	var r0 *entity.Withdraw
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Withdraw); ok {
		r0 = rf(ctx, withdrawID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Withdraw)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, withdrawID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWithdrawGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewWithdrawGetter creates a new instance of WithdrawGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWithdrawGetter(t mockConstructorTestingTNewWithdrawGetter) *WithdrawGetter {
	mock := &WithdrawGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
