// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WithdrawRemover is an autogenerated mock type for the WithdrawRemover type
type WithdrawRemover struct {
	mock.Mock
}

// Remove provides a mock function with given fields: ctx, withdrawID
func (_m *WithdrawRemover) Remove(ctx context.Context, withdrawID uuid.UUID) error {
	ret := _m.Called(ctx, withdrawID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, withdrawID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewWithdrawRemover interface {
	mock.TestingT
	Cleanup(func())
}

// NewWithdrawRemover creates a new instance of WithdrawRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWithdrawRemover(t mockConstructorTestingTNewWithdrawRemover) *WithdrawRemover {
	mock := &WithdrawRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
