// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// WithdrawAdder is an autogenerated mock type for the WithdrawAdder type
type WithdrawAdder struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, order
func (_m *WithdrawAdder) Add(ctx context.Context, order *entity.Withdraw) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Withdraw) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewWithdrawAdder interface {
	mock.TestingT
	Cleanup(func())
}

// NewWithdrawAdder creates a new instance of WithdrawAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWithdrawAdder(t mockConstructorTestingTNewWithdrawAdder) *WithdrawAdder {
	mock := &WithdrawAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
