// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// WithdrawTransactionalAdder is an autogenerated mock type for the WithdrawTransactionalAdder type
type WithdrawTransactionalAdder struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, order
func (_m *WithdrawTransactionalAdder) Add(ctx context.Context, order *entity.Withdraw) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Withdraw) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithinTransaction provides a mock function with given fields: ctx, tFunc
func (_m *WithdrawTransactionalAdder) WithinTransaction(ctx context.Context, tFunc func(context.Context) error) error {
	ret := _m.Called(ctx, tFunc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, tFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewWithdrawTransactionalAdder interface {
	mock.TestingT
	Cleanup(func())
}

// NewWithdrawTransactionalAdder creates a new instance of WithdrawTransactionalAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWithdrawTransactionalAdder(t mockConstructorTestingTNewWithdrawTransactionalAdder) *WithdrawTransactionalAdder {
	mock := &WithdrawTransactionalAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
