// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// WithdrawChanger is an autogenerated mock type for the WithdrawChanger type
type WithdrawChanger struct {
	mock.Mock
}

type WithdrawChanger_Expecter struct {
	mock *mock.Mock
}

func (_m *WithdrawChanger) EXPECT() *WithdrawChanger_Expecter {
	return &WithdrawChanger_Expecter{mock: &_m.Mock}
}

// Change provides a mock function with given fields: ctx, order
func (_m *WithdrawChanger) Change(ctx context.Context, order *entity.Withdraw) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Withdraw) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithdrawChanger_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type WithdrawChanger_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//  - ctx context.Context
//  - order *entity.Withdraw
func (_e *WithdrawChanger_Expecter) Change(ctx interface{}, order interface{}) *WithdrawChanger_Change_Call {
	return &WithdrawChanger_Change_Call{Call: _e.mock.On("Change", ctx, order)}
}

func (_c *WithdrawChanger_Change_Call) Run(run func(ctx context.Context, order *entity.Withdraw)) *WithdrawChanger_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Withdraw))
	})
	return _c
}

func (_c *WithdrawChanger_Change_Call) Return(_a0 error) *WithdrawChanger_Change_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewWithdrawChanger interface {
	mock.TestingT
	Cleanup(func())
}

// NewWithdrawChanger creates a new instance of WithdrawChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWithdrawChanger(t mockConstructorTestingTNewWithdrawChanger) *WithdrawChanger {
	mock := &WithdrawChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
