// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// WithdrawTransactionalAdder is an autogenerated mock type for the WithdrawTransactionalAdder type
type WithdrawTransactionalAdder struct {
	mock.Mock
}

type WithdrawTransactionalAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *WithdrawTransactionalAdder) EXPECT() *WithdrawTransactionalAdder_Expecter {
	return &WithdrawTransactionalAdder_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, order
func (_m *WithdrawTransactionalAdder) Add(ctx context.Context, order *entity.Withdraw) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Withdraw) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithdrawTransactionalAdder_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type WithdrawTransactionalAdder_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//  - ctx context.Context
//  - order *entity.Withdraw
func (_e *WithdrawTransactionalAdder_Expecter) Add(ctx interface{}, order interface{}) *WithdrawTransactionalAdder_Add_Call {
	return &WithdrawTransactionalAdder_Add_Call{Call: _e.mock.On("Add", ctx, order)}
}

func (_c *WithdrawTransactionalAdder_Add_Call) Run(run func(ctx context.Context, order *entity.Withdraw)) *WithdrawTransactionalAdder_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Withdraw))
	})
	return _c
}

func (_c *WithdrawTransactionalAdder_Add_Call) Return(_a0 error) *WithdrawTransactionalAdder_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

// WithinTransaction provides a mock function with given fields: ctx, tFunc
func (_m *WithdrawTransactionalAdder) WithinTransaction(ctx context.Context, tFunc func(context.Context) error) error {
	ret := _m.Called(ctx, tFunc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, tFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithdrawTransactionalAdder_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type WithdrawTransactionalAdder_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//  - ctx context.Context
//  - tFunc func(context.Context) error
func (_e *WithdrawTransactionalAdder_Expecter) WithinTransaction(ctx interface{}, tFunc interface{}) *WithdrawTransactionalAdder_WithinTransaction_Call {
	return &WithdrawTransactionalAdder_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", ctx, tFunc)}
}

func (_c *WithdrawTransactionalAdder_WithinTransaction_Call) Run(run func(ctx context.Context, tFunc func(context.Context) error)) *WithdrawTransactionalAdder_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *WithdrawTransactionalAdder_WithinTransaction_Call) Return(_a0 error) *WithdrawTransactionalAdder_WithinTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewWithdrawTransactionalAdder interface {
	mock.TestingT
	Cleanup(func())
}

// NewWithdrawTransactionalAdder creates a new instance of WithdrawTransactionalAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWithdrawTransactionalAdder(t mockConstructorTestingTNewWithdrawTransactionalAdder) *WithdrawTransactionalAdder {
	mock := &WithdrawTransactionalAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
