// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-1-project/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// WithdrawChanger is an autogenerated mock type for the WithdrawChanger type
type WithdrawChanger struct {
	mock.Mock
}

// Change provides a mock function with given fields: ctx, order
func (_m *WithdrawChanger) Change(ctx context.Context, order *entity.Withdraw) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Withdraw) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewWithdrawChanger interface {
	mock.TestingT
	Cleanup(func())
}

// NewWithdrawChanger creates a new instance of WithdrawChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWithdrawChanger(t mockConstructorTestingTNewWithdrawChanger) *WithdrawChanger {
	mock := &WithdrawChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
